/**
 * Compact LeetCode-compatible Python signatures used when the official API
 * withholds code snippets for premium problems.
 *
 * Method/class names and parameter names are interface facts. The catalog is
 * generated from the CC BY-SA 4.0 doocs/leetcode solution index; it contains
 * no solution implementations. Source: https://github.com/doocs/leetcode
 */
export const OFFLINE_PYTHON_SIGNATURES: Record<string, string> = {
  "3sum-smaller": "class Solution:\n    def threeSumSmaller(self, nums, target):\n        pass",
  "4-keys-keyboard": "class Solution:\n    def maxA(self, n):\n        pass",
  "add-bold-tag-in-string": "class Solution:\n    def addBoldTag(self, s, words):\n        pass",
  "add-two-polynomials-represented-as-linked-lists": "class Solution:\n    def addPoly(self, poly1, poly2):\n        pass",
  "alien-dictionary": "class Solution:\n    def alienOrder(self, words):\n        pass",
  "all-paths-from-source-lead-to-destination": "class Solution:\n    def leadsToDestination(self, n, edges, source, destination):\n        pass",
  "amount-of-new-area-painted-each-day": "class Solution:\n    def amountPainted(self, paint):\n        pass",
  "analyze-user-website-visit-pattern": "class Solution:\n    def mostVisitedPattern(self, username, timestamp, website):\n        pass",
  "android-unlock-patterns": "class Solution:\n    def numberOfPatterns(self, m, n):\n        pass",
  "apply-substitutions": "class Solution:\n    def applySubstitutions(self, replacements, text):\n        pass",
  "armstrong-number": "class Solution:\n    def isArmstrong(self, n):\n        pass",
  "basic-calculator-iii": "class Solution:\n    def calculate(self, s):\n        pass",
  "best-meeting-point": "class Solution:\n    def minTotalDistance(self, grid):\n        pass",
  "binary-searchable-numbers-in-an-unsorted-array": "class Solution:\n    def binarySearchableNumbers(self, nums):\n        pass",
  "binary-tree-longest-consecutive-sequence": "class Solution:\n    def longestConsecutive(self, root):\n        pass",
  "binary-tree-longest-consecutive-sequence-ii": "class Solution:\n    def longestConsecutive(self, root):\n        pass",
  "binary-tree-upside-down": "class Solution:\n    def upsideDownBinaryTree(self, root):\n        pass",
  "binary-tree-vertical-order-traversal": "class Solution:\n    def verticalOrder(self, root):\n        pass",
  "bitwise-or-of-adjacent-elements": "class Solution:\n    def orArray(self, nums):\n        pass",
  "bold-words-in-string": "class Solution:\n    def boldWords(self, words, s):\n        pass",
  "bomb-enemy": "class Solution:\n    def maxKilledEnemies(self, grid):\n        pass",
  "boundary-of-binary-tree": "class Solution:\n    def boundaryOfBinaryTree(self, root):\n        pass",
  "brace-expansion": "class Solution:\n    def expand(self, s):\n        pass",
  "brightest-position-on-street": "class Solution:\n    def brightestPosition(self, lights):\n        pass",
  "buildings-with-an-ocean-view": "class Solution:\n    def findBuildings(self, heights):\n        pass",
  "campus-bikes": "class Solution:\n    def assignBikes(self, workers, bikes):\n        pass",
  "campus-bikes-ii": "class Solution:\n    def assignBikes(self, workers, bikes):\n        pass",
  "candy-crush": "class Solution:\n    def candyCrush(self, board):\n        pass",
  "change-the-root-of-a-binary-tree": "class Solution:\n    def flipBinaryTree(self, root, leaf):\n        pass",
  "check-for-contradictions-in-equations": "class Solution:\n    def checkContradictions(self, equations, values):\n        pass",
  "check-if-a-number-is-majority-element-in-a-sorted-array": "class Solution:\n    def isMajorityElement(self, nums, target):\n        pass",
  "check-if-there-is-a-path-with-equal-number-of-0s-and-1s": "class Solution:\n    def isThereAPath(self, grid):\n        pass",
  "check-if-two-expression-trees-are-equivalent": "class Solution:\n    def checkEquivalence(self, root1, root2):\n        pass",
  "checking-existence-of-edge-length-limited-paths-ii": "class DistanceLimitedPathsExist:\n    def __init__(self, n, edgeList):\n        pass",
  "choose-numbers-from-two-arrays-in-range": "class Solution:\n    def countSubranges(self, nums1, nums2):\n        pass",
  "clone-binary-tree-with-random-pointer": "class Solution:\n    def copyRandomBinaryTree(self, root):\n        pass",
  "clone-n-ary-tree": "class Solution:\n    def cloneTree(self, root):\n        pass",
  "closest-binary-search-tree-value": "class Solution:\n    def closestValue(self, root, target):\n        pass",
  "closest-binary-search-tree-value-ii": "class Solution:\n    def closestKValues(self, root, target, k):\n        pass",
  "closest-leaf-in-a-binary-tree": "class Solution:\n    def findClosestLeaf(self, root, k):\n        pass",
  "coin-path": "class Solution:\n    def cheapestJump(self, coins, maxJump):\n        pass",
  "confusing-number": "class Solution:\n    def confusingNumber(self, n):\n        pass",
  "confusing-number-ii": "class Solution:\n    def confusingNumberII(self, n):\n        pass",
  "connecting-cities-with-minimum-cost": "class Solution:\n    def minimumCost(self, n, connections):\n        pass",
  "construct-binary-tree-from-string": "class Solution:\n    def str2tree(self, s):\n        pass",
  "convert-binary-search-tree-to-sorted-doubly-linked-list": "class Solution:\n    def treeToDoublyList(self, root):\n        pass",
  "convex-polygon": "class Solution:\n    def isConvex(self, points):\n        pass",
  "correct-a-binary-tree": "class Solution:\n    def correctBinaryTree(self, root):\n        pass",
  "count-houses-in-a-circular-street": "class Solution:\n    def houseCount(self, street, k):\n        pass",
  "count-numbers-with-unique-digits-ii": "class Solution:\n    def numberCount(self, a, b):\n        pass",
  "count-pairs-in-two-arrays": "class Solution:\n    def countPairs(self, nums1, nums2):\n        pass",
  "count-pairs-of-equal-substrings-with-minimum-difference": "class Solution:\n    def countQuadruples(self, firstString, secondString):\n        pass",
  "count-positions-on-street-with-required-brightness": "class Solution:\n    def meetRequirement(self, n, lights, requirement):\n        pass",
  "count-subarrays-with-more-ones-than-zeros": "class Solution:\n    def subarraysWithMoreZerosThanOnes(self, nums):\n        pass",
  "count-the-number-of-good-subsequences": "class Solution:\n    def countGoodSubsequences(self, s):\n        pass",
  "count-the-number-of-k-big-indices": "class Solution:\n    def kBigIndices(self, nums, k):\n        pass",
  "count-the-number-of-k-free-subsets": "class Solution:\n    def countTheNumOfKFreeSubsets(self, nums, k):\n        pass",
  "count-triplets-with-even-xor-set-bits-i": "class Solution:\n    def tripletCount(self, a, b, c):\n        pass",
  "count-triplets-with-even-xor-set-bits-ii": "class Solution:\n    def tripletCount(self, a, b, c):\n        pass",
  "count-univalue-subtrees": "class Solution:\n    def countUnivalSubtrees(self, root):\n        pass",
  "count-ways-to-distribute-candies": "class Solution:\n    def waysToDistribute(self, n, k):\n        pass",
  "cutting-ribbons": "class Solution:\n    def maxLength(self, ribbons, k):\n        pass",
  "design-a-leaderboard": "class Leaderboard:\n    def __init__(self):\n        pass",
  "design-an-array-statistics-tracker": "class StatisticsTracker:\n    def __init__(self):\n        pass",
  "design-an-expression-tree-with-evaluate-function": "class TreeBuilder:\n    def __init__(self):\n        pass",
  "design-bounded-blocking-queue": "class BoundedBlockingQueue:\n    def __init__(self, capacity):\n        pass",
  "design-compressed-string-iterator": "class StringIterator:\n    def __init__(self, compressedString):\n        pass",
  "design-file-system": "class FileSystem:\n    def __init__(self):\n        pass",
  "design-hit-counter": "class HitCounter:\n    def __init__(self):\n        pass",
  "design-in-memory-file-system": "class FileSystem:\n    def __init__(self):\n        pass",
  "design-log-storage-system": "class LogSystem:\n    def __init__(self):\n        pass",
  "design-most-recently-used-queue": "class MRUQueue:\n    def __init__(self, n):\n        pass",
  "design-phone-directory": "class PhoneDirectory:\n    def __init__(self, maxNumbers):\n        pass",
  "design-search-autocomplete-system": "class AutocompleteSystem:\n    def __init__(self, sentences, times):\n        pass",
  "design-snake-game": "class SnakeGame:\n    def __init__(self, width, height, food):\n        pass",
  "design-tic-tac-toe": "class TicTacToe:\n    def __init__(self, n):\n        pass",
  "diameter-of-n-ary-tree": "class Solution:\n    def diameter(self, root):\n        pass",
  "diet-plan-performance": "class Solution:\n    def dietPlanPerformance(self, calories, k, lower, upper):\n        pass",
  "digit-count-in-range": "class Solution:\n    def digitsCount(self, d, low, high):\n        pass",
  "distinct-numbers-in-each-subarray": "class Solution:\n    def distinctNumbers(self, nums, k):\n        pass",
  "distribute-candies-among-children-iii": "class Solution:\n    def distributeCandies(self, n, limit):\n        pass",
  "divide-array-into-increasing-sequences": "class Solution:\n    def canDivideIntoSubsequences(self, nums, k):\n        pass",
  "divide-chocolate": "class Solution:\n    def maximizeSweetness(self, sweetness, k):\n        pass",
  "dot-product-of-two-sparse-vectors": "class SparseVector:\n    def __init__(self, nums):\n        pass",
  "employee-free-time": "class Solution:\n    def employeeFreeTime(self, schedule):\n        pass",
  "encode-and-decode-strings": "class Codec:\n    def __init__(self):\n        pass",
  "encode-string-with-shortest-length": "class Solution:\n    def encode(self, s):\n        pass",
  "equal-tree-partition": "class Solution:\n    def checkEqualTree(self, root):\n        pass",
  "equalize-strings-by-adding-or-removing-characters-at-ends": "class Solution:\n    def minOperations(self, initial, target):\n        pass",
  "extract-kth-character-from-the-rope-tree": "class Solution:\n    def getKthCharacter(self, root, k):\n        pass",
  "factor-combinations": "class Solution:\n    def getFactors(self, n):\n        pass",
  "find-anagram-mappings": "class Solution:\n    def anagramMappings(self, nums1, nums2):\n        pass",
  "find-distance-in-a-binary-tree": "class Solution:\n    def findDistance(self, root, p, q):\n        pass",
  "find-k-length-substrings-with-no-repeated-characters": "class Solution:\n    def numKLenSubstrNoRepeats(self, s, k):\n        pass",
  "find-leaves-of-binary-tree": "class Solution:\n    def findLeaves(self, root):\n        pass",
  "find-longest-self-contained-substring": "class Solution:\n    def maxSubstringLength(self, s):\n        pass",
  "find-minimum-time-to-finish-all-jobs-ii": "class Solution:\n    def minimumTime(self, jobs, workers):\n        pass",
  "find-nearest-right-node-in-binary-tree": "class Solution:\n    def findNearestRightNode(self, root, u):\n        pass",
  "find-pattern-in-infinite-stream-i": "class Solution:\n    def findPattern(self, stream, pattern):\n        pass",
  "find-permutation": "class Solution:\n    def findPermutation(self, s):\n        pass",
  "find-root-of-n-ary-tree": "class Solution:\n    def findRoot(self, tree):\n        pass",
  "find-smallest-common-element-in-all-rows": "class Solution:\n    def smallestCommonElement(self, mat):\n        pass",
  "find-the-celebrity": "class Solution:\n    def findCelebrity(self, n):\n        pass",
  "find-the-index-of-the-large-integer": "class Solution:\n    def getIndex(self, reader):\n        pass",
  "find-the-last-marked-nodes-in-tree": "class Solution:\n    def lastMarkedNodes(self, edges):\n        pass",
  "finding-the-number-of-visible-mountains": "class Solution:\n    def visibleMountains(self, peaks):\n        pass",
  "first-unique-number": "class FirstUnique:\n    def __init__(self, nums):\n        pass",
  "fixed-point": "class Solution:\n    def fixedPoint(self, arr):\n        pass",
  "flatten-2d-vector": "class Vector2D:\n    def __init__(self, vec):\n        pass",
  "flip-game": "class Solution:\n    def generatePossibleNextMoves(self, currentState):\n        pass",
  "flip-game-ii": "class Solution:\n    def canWin(self, currentState):\n        pass",
  "generalized-abbreviation": "class Solution:\n    def generateAbbreviations(self, word):\n        pass",
  "graph-valid-tree": "class Solution:\n    def validTree(self, n, edges):\n        pass",
  "group-shifted-strings": "class Solution:\n    def groupStrings(self, strings):\n        pass",
  "guess-the-majority-in-a-hidden-array": "class Solution:\n    def guessMajority(self, reader):\n        pass",
  "high-five": "class Solution:\n    def highFive(self, items):\n        pass",
  "implement-trie-ii-prefix-tree": "class Trie:\n    def __init__(self):\n        pass",
  "index-pairs-of-a-string": "class Solution:\n    def indexPairs(self, text, words):\n        pass",
  "inorder-successor-in-bst": "class Solution:\n    def inorderSuccessor(self, root, p):\n        pass",
  "inorder-successor-in-bst-ii": "class Solution:\n    def inorderSuccessor(self, node):\n        pass",
  "insert-into-a-sorted-circular-linked-list": "class Solution:\n    def insert(self, head, insertVal):\n        pass",
  "intersection-of-three-sorted-arrays": "class Solution:\n    def arraysIntersection(self, arr1, arr2, arr3):\n        pass",
  "jump-game-viii": "class Solution:\n    def minCost(self, nums, costs):\n        pass",
  "k-empty-slots": "class Solution:\n    def kEmptySlots(self, bulbs, k):\n        pass",
  "kill-process": "class Solution:\n    def killProcess(self, pid, ppid, kill):\n        pass",
  "kth-smallest-subarray-sum": "class Solution:\n    def kthSmallestSubarraySum(self, nums, k):\n        pass",
  "largest-subarray-length-k": "class Solution:\n    def largestSubarray(self, nums, k):\n        pass",
  "largest-unique-number": "class Solution:\n    def largestUniqueNumber(self, nums):\n        pass",
  "leftmost-column-with-at-least-a-one": "class Solution:\n    def leftMostColumnWithOne(self, binaryMatrix):\n        pass",
  "line-reflection": "class Solution:\n    def isReflected(self, points):\n        pass",
  "logger-rate-limiter": "class Logger:\n    def __init__(self):\n        pass",
  "lonely-pixel-i": "class Solution:\n    def findLonelyPixel(self, picture):\n        pass",
  "lonely-pixel-ii": "class Solution:\n    def findBlackPixel(self, picture, target):\n        pass",
  "longest-common-subsequence-between-sorted-arrays": "class Solution:\n    def longestCommonSubsequence(self, arrays):\n        pass",
  "longest-line-of-consecutive-one-in-matrix": "class Solution:\n    def longestLine(self, mat):\n        pass",
  "longest-repeating-substring": "class Solution:\n    def longestRepeatingSubstring(self, s):\n        pass",
  "longest-substring-with-at-most-k-distinct-characters": "class Solution:\n    def lengthOfLongestSubstringKDistinct(self, s, k):\n        pass",
  "longest-substring-with-at-most-two-distinct-characters": "class Solution:\n    def lengthOfLongestSubstringTwoDistinct(self, s):\n        pass",
  "longest-word-with-all-prefixes": "class Solution:\n    def longestWord(self, words):\n        pass",
  "lowest-common-ancestor-of-a-binary-tree-iii": "class Solution:\n    def lowestCommonAncestor(self, p, q):\n        pass",
  "lowest-common-ancestor-of-a-binary-tree-iv": "class Solution:\n    def lowestCommonAncestor(self, root, nodes):\n        pass",
  "make-array-non-decreasing-or-non-increasing": "class Solution:\n    def convertArray(self, nums):\n        pass",
  "match-alphanumerical-pattern-in-matrix-i": "class Solution:\n    def findPattern(self, board, pattern):\n        pass",
  "max-consecutive-ones-ii": "class Solution:\n    def findMaxConsecutiveOnes(self, nums):\n        pass",
  "max-stack": "class MaxStack:\n    def __init__(self):\n        pass",
  "maximal-range-that-each-element-is-maximum-in-it": "class Solution:\n    def maximumLengthOfRanges(self, nums):\n        pass",
  "maximize-the-beauty-of-the-garden": "class Solution:\n    def maximumBeauty(self, flowers):\n        pass",
  "maximize-total-tastiness-of-purchased-fruits": "class Solution:\n    def maxTastiness(self, price, tastiness, maxAmount, maxCoupons):\n        pass",
  "maximum-alternating-subarray-sum": "class Solution:\n    def maximumAlternatingSubarraySum(self, nums):\n        pass",
  "maximum-average-subarray-ii": "class Solution:\n    def findMaxAverage(self, nums, k):\n        pass",
  "maximum-average-subtree": "class Solution:\n    def maximumAverageSubtree(self, root):\n        pass",
  "maximum-calories-burnt-from-jumps": "class Solution:\n    def maxCaloriesBurnt(self, heights):\n        pass",
  "maximum-coin-collection": "class Solution:\n    def maxCoins(self, lane1, lane2):\n        pass",
  "maximum-font-to-fit-a-sentence-in-a-screen": "class Solution:\n    def maxFont(self, text, w, h, fonts, fontInfo):\n        pass",
  "maximum-increasing-triplet-value": "class Solution:\n    def maximumTripletValue(self, nums):\n        pass",
  "maximum-length-of-semi-decreasing-subarrays": "class Solution:\n    def maxSubarrayLength(self, nums):\n        pass",
  "maximum-linear-stock-score": "class Solution:\n    def maxScore(self, prices):\n        pass",
  "maximum-number-of-accepted-invitations": "class Solution:\n    def maximumInvitations(self, grid):\n        pass",
  "maximum-number-of-books-you-can-take": "class Solution:\n    def maximumBooks(self, books):\n        pass",
  "maximum-number-that-makes-result-of-bitwise-and-zero": "class Solution:\n    def maxNumber(self, n):\n        pass",
  "maximum-of-minimum-values-in-all-subarrays": "class Solution:\n    def findMaximums(self, nums):\n        pass",
  "maximum-profit-from-trading-stocks": "class Solution:\n    def maximumProfit(self, present, future, budget):\n        pass",
  "maximum-size-subarray-sum-equals-k": "class Solution:\n    def maxSubArrayLen(self, nums, k):\n        pass",
  "maximum-sum-score-of-array": "class Solution:\n    def maximumSumScore(self, nums):\n        pass",
  "maximum-team-size-with-overlapping-intervals": "class Solution:\n    def maximumTeamSize(self, startTime, endTime):\n        pass",
  "maximum-vacation-days": "class Solution:\n    def maxVacationDays(self, flights, days):\n        pass",
  "meeting-rooms": "class Solution:\n    def canAttendMeetings(self, intervals):\n        pass",
  "meeting-rooms-ii": "class Solution:\n    def minMeetingRooms(self, intervals):\n        pass",
  "meeting-scheduler": "class Solution:\n    def minAvailableDuration(self, slots1, slots2, duration):\n        pass",
  "merge-operations-to-turn-array-into-a-palindrome": "class Solution:\n    def minimumOperations(self, nums):\n        pass",
  "minimize-max-distance-to-gas-station": "class Solution:\n    def minmaxGasDist(self, stations, k):\n        pass",
  "minimize-maximum-value-in-a-grid": "class Solution:\n    def minScore(self, grid):\n        pass",
  "minimize-product-sum-of-two-arrays": "class Solution:\n    def minProductSum(self, nums1, nums2):\n        pass",
  "minimize-rounding-error-to-meet-target": "class Solution:\n    def minimizeError(self, prices, target):\n        pass",
  "minimizing-array-after-replacing-pairs-with-their-product": "class Solution:\n    def minArrayLength(self, nums, k):\n        pass",
  "minimum-adjacent-swaps-to-make-a-valid-array": "class Solution:\n    def minimumSwaps(self, nums):\n        pass",
  "minimum-cost-to-connect-sticks": "class Solution:\n    def connectSticks(self, sticks):\n        pass",
  "minimum-factorization": "class Solution:\n    def smallestFactorization(self, num):\n        pass",
  "minimum-flips-in-binary-tree-to-get-result": "class Solution:\n    def minimumFlips(self, root, result):\n        pass",
  "minimum-health-to-beat-game": "class Solution:\n    def minimumHealth(self, damage, armor):\n        pass",
  "minimum-knight-moves": "class Solution:\n    def minKnightMoves(self, x, y):\n        pass",
  "minimum-number-of-keypresses": "class Solution:\n    def minimumKeypresses(self, s):\n        pass",
  "minimum-number-of-primes-to-sum-to-target": "class Solution:\n    def minNumberOfPrimes(self, n, m):\n        pass",
  "minimum-operations-to-remove-adjacent-ones-in-matrix": "class Solution:\n    def minimumOperations(self, grid):\n        pass",
  "minimum-path-cost-in-a-hidden-grid": "class Solution:\n    def findShortestPath(self, master):\n        pass",
  "minimum-swaps-to-group-all-1s-together": "class Solution:\n    def minSwaps(self, data):\n        pass",
  "minimum-time-to-build-blocks": "class Solution:\n    def minBuildTime(self, blocks, split):\n        pass",
  "minimum-window-subsequence": "class Solution:\n    def minWindow(self, s1, s2):\n        pass",
  "missing-element-in-sorted-array": "class Solution:\n    def missingElement(self, nums, k):\n        pass",
  "missing-number-in-arithmetic-progression": "class Solution:\n    def missingNumber(self, arr):\n        pass",
  "missing-ranges": "class Solution:\n    def findMissingRanges(self, nums, lower, upper):\n        pass",
  "most-expensive-item-that-can-not-be-bought": "class Solution:\n    def mostExpensiveItem(self, primeOne, primeTwo):\n        pass",
  "moving-average-from-data-stream": "class MovingAverage:\n    def __init__(self, size):\n        pass",
  "nested-list-weight-sum": "class Solution:\n    def depthSum(self, nestedList):\n        pass",
  "nested-list-weight-sum-ii": "class Solution:\n    def depthSumInverse(self, nestedList):\n        pass",
  "next-closest-time": "class Solution:\n    def nextClosestTime(self, time):\n        pass",
  "next-palindrome-using-same-digits": "class Solution:\n    def nextPalindrome(self, num):\n        pass",
  "number-of-connected-components-in-an-undirected-graph": "class Solution:\n    def countComponents(self, n, edges):\n        pass",
  "number-of-days-in-a-month": "class Solution:\n    def numberOfDays(self, year, month):\n        pass",
  "number-of-distinct-islands": "class Solution:\n    def numDistinctIslands(self, grid):\n        pass",
  "number-of-distinct-islands-ii": "class Solution:\n    def numDistinctIslands2(self, grid):\n        pass",
  "number-of-distinct-substrings-in-a-string": "class Solution:\n    def countDistinct(self, s):\n        pass",
  "number-of-divisible-triplet-sums": "class Solution:\n    def divisibleTripletCount(self, nums, d):\n        pass",
  "number-of-equal-numbers-blocks": "class Solution:\n    def countBlocks(self, nums):\n        pass",
  "number-of-islands-ii": "class Solution:\n    def numIslands2(self, m, n, positions):\n        pass",
  "number-of-people-that-can-be-seen-in-a-grid": "class Solution:\n    def seePeople(self, heights):\n        pass",
  "number-of-same-end-substrings": "class Solution:\n    def sameEndSubstringCount(self, s, queries):\n        pass",
  "number-of-self-divisible-permutations": "class Solution:\n    def selfDivisiblePermutationCount(self, n):\n        pass",
  "number-of-unique-categories": "class Solution:\n    def numberOfCategories(self, n, categoryHandler):\n        pass",
  "number-of-ways-to-build-house-of-cards": "class Solution:\n    def houseOfCards(self, n):\n        pass",
  "number-of-ways-to-build-sturdy-brick-wall": "class Solution:\n    def buildWall(self, height, width, bricks):\n        pass",
  "number-of-ways-to-reach-destination-in-the-grid": "class Solution:\n    def numberOfWays(self, n, m, k, source, dest):\n        pass",
  "optimal-account-balancing": "class Solution:\n    def minTransfers(self, transactions):\n        pass",
  "optimize-water-distribution-in-a-village": "class Solution:\n    def minCostToSupplyWater(self, n, wells, pipes):\n        pass",
  "output-contest-matches": "class Solution:\n    def findContestMatch(self, n):\n        pass",
  "paint-fence": "class Solution:\n    def numWays(self, n, k):\n        pass",
  "paint-house": "class Solution:\n    def minCost(self, costs):\n        pass",
  "palindrome-permutation": "class Solution:\n    def canPermutePalindrome(self, s):\n        pass",
  "parallel-courses": "class Solution:\n    def minimumSemesters(self, n, relations):\n        pass",
  "path-sum-iv": "class Solution:\n    def pathSum(self, nums):\n        pass",
  "path-with-maximum-minimum-value": "class Solution:\n    def maximumMinimumPath(self, grid):\n        pass",
  "paths-in-maze-that-lead-to-same-room": "class Solution:\n    def numberOfPaths(self, n, corridors):\n        pass",
  "plus-one-linked-list": "class Solution:\n    def plusOne(self, head):\n        pass",
  "pour-water": "class Solution:\n    def pourWater(self, heights, volume, k):\n        pass",
  "power-update-after-k-th-largest-insertion-i": "class Solution:\n    def powerUpdate(self, nums, p, queries):\n        pass",
  "put-boxes-into-the-warehouse-i": "class Solution:\n    def maxBoxesInWarehouse(self, boxes, warehouse):\n        pass",
  "put-boxes-into-the-warehouse-ii": "class Solution:\n    def maxBoxesInWarehouse(self, boxes, warehouse):\n        pass",
  "range-addition": "class Solution:\n    def getModifiedArray(self, length, updates):\n        pass",
  "range-sum-query-2d-mutable": "class NumMatrix:\n    def __init__(self, matrix):\n        pass",
  "read-n-characters-given-read4": "class Solution:\n    def read(self, buf, n):\n        pass",
  "read-n-characters-given-read4-ii-call-multiple-times": "class Solution:\n    def __init__(self):\n        pass",
  "rearrange-string-k-distance-apart": "class Solution:\n    def rearrangeString(self, s, k):\n        pass",
  "remove-all-ones-with-row-and-column-flips": "class Solution:\n    def removeOnes(self, grid):\n        pass",
  "remove-all-ones-with-row-and-column-flips-ii": "class Solution:\n    def removeOnes(self, grid):\n        pass",
  "remove-duplicates-from-an-unsorted-linked-list": "class Solution:\n    def deleteDuplicatesUnsorted(self, head):\n        pass",
  "remove-interval": "class Solution:\n    def removeInterval(self, intervals, toBeRemoved):\n        pass",
  "remove-vowels-from-a-string": "class Solution:\n    def removeVowels(self, s):\n        pass",
  "reverse-words-in-a-string-ii": "class Solution:\n    def reverseWords(self, s) -> None:\n        pass",
  "robot-room-cleaner": "class Solution:\n    def cleanRoom(self, robot):\n        pass",
  "search-in-a-sorted-array-of-unknown-size": "class Solution:\n    def search(self, reader, target):\n        pass",
  "sentence-screen-fitting": "class Solution:\n    def wordsTyping(self, sentence, rows, cols):\n        pass",
  "sentence-similarity": "class Solution:\n    def areSentencesSimilar(self, sentence1, sentence2, similarPairs):\n        pass",
  "sentence-similarity-ii": "class Solution:\n    def areSentencesSimilarTwo(self, sentence1, sentence2, similarPairs):\n        pass",
  "sequence-reconstruction": "class Solution:\n    def sequenceReconstruction(self, nums, sequences):\n        pass",
  "serialize-and-deserialize-n-ary-tree": "class Codec:\n    def __init__(self):\n        pass",
  "shortest-distance-from-all-buildings": "class Solution:\n    def shortestDistance(self, grid):\n        pass",
  "shortest-distance-to-target-color": "class Solution:\n    def shortestDistanceColor(self, colors, queries):\n        pass",
  "shortest-path-in-a-hidden-grid": "class Solution:\n    def findShortestPath(self, master):\n        pass",
  "shortest-way-to-form-string": "class Solution:\n    def shortestWay(self, source, target):\n        pass",
  "shortest-word-distance": "class Solution:\n    def shortestDistance(self, wordsDict, word1, word2):\n        pass",
  "shortest-word-distance-ii": "class WordDistance:\n    def __init__(self, wordsDict):\n        pass",
  "shortest-word-distance-iii": "class Solution:\n    def shortestWordDistance(self, wordsDict, word1, word2):\n        pass",
  "similar-rgb-color": "class Solution:\n    def similarRGB(self, color):\n        pass",
  "single-row-keyboard": "class Solution:\n    def calculateTime(self, keyboard, word):\n        pass",
  "smallest-common-region": "class Solution:\n    def findSmallestRegion(self, regions, region1, region2):\n        pass",
  "smallest-rectangle-enclosing-black-pixels": "class Solution:\n    def minArea(self, image, x, y):\n        pass",
  "sort-array-by-moving-items-to-empty-space": "class Solution:\n    def sortArray(self, nums):\n        pass",
  "sort-features-by-popularity": "class Solution:\n    def sortFeatures(self, features, responses):\n        pass",
  "sort-transformed-array": "class Solution:\n    def sortTransformedArray(self, nums, a, b, c):\n        pass",
  "sparse-matrix-multiplication": "class Solution:\n    def multiply(self, mat1, mat2):\n        pass",
  "split-array-with-equal-sum": "class Solution:\n    def splitArray(self, nums):\n        pass",
  "split-bst": "class Solution:\n    def splitBST(self, root, target):\n        pass",
  "split-concatenated-strings": "class Solution:\n    def splitLoopedString(self, strs):\n        pass",
  "string-transforms-into-another-string": "class Solution:\n    def canConvert(self, str1, str2):\n        pass",
  "strings-differ-by-one-character": "class Solution:\n    def differByOne(self, dict):\n        pass",
  "strobogrammatic-number": "class Solution:\n    def isStrobogrammatic(self, num):\n        pass",
  "strobogrammatic-number-ii": "class Solution:\n    def findStrobogrammatic(self, n):\n        pass",
  "sum-of-digits-in-the-minimum-number": "class Solution:\n    def sumOfDigits(self, nums):\n        pass",
  "the-earliest-moment-when-everyone-become-friends": "class Solution:\n    def earliestAcq(self, logs, n):\n        pass",
  "the-maze": "class Solution:\n    def hasPath(self, maze, start, destination):\n        pass",
  "the-maze-ii": "class Solution:\n    def shortestDistance(self, maze, start, destination):\n        pass",
  "the-maze-iii": "class Solution:\n    def findShortestWay(self, maze, ball, hole):\n        pass",
  "the-most-similar-path-in-a-graph": "class Solution:\n    def mostSimilar(self, n, roads, names, targetPath):\n        pass",
  "time-taken-to-cross-the-door": "class Solution:\n    def timeTaken(self, arrival, state):\n        pass",
  "tree-diameter": "class Solution:\n    def treeDiameter(self, edges):\n        pass",
  "two-sum-bsts": "class Solution:\n    def twoSumBSTs(self, root1, root2, target):\n        pass",
  "two-sum-iii-data-structure-design": "class TwoSum:\n    def __init__(self):\n        pass",
  "two-sum-less-than-k": "class Solution:\n    def twoSumLessThanK(self, nums, k):\n        pass",
  "unique-word-abbreviation": "class ValidWordAbbr:\n    def __init__(self, dictionary):\n        pass",
  "unit-conversion-ii": "class Solution:\n    def queryConversions(self, conversions, queries):\n        pass",
  "valid-palindrome-iii": "class Solution:\n    def isValidPalindrome(self, s, k):\n        pass",
  "valid-palindrome-iv": "class Solution:\n    def makePalindrome(self, s):\n        pass",
  "valid-word-abbreviation": "class Solution:\n    def validWordAbbreviation(self, word, abbr):\n        pass",
  "valid-word-square": "class Solution:\n    def validWordSquare(self, words):\n        pass",
  "verify-preorder-sequence-in-binary-search-tree": "class Solution:\n    def verifyPreorder(self, preorder):\n        pass",
  "walls-and-gates": "class Solution:\n    def wallsAndGates(self, rooms) -> None:\n        pass",
  "web-crawler": "class Solution:\n    def crawl(self, startUrl, htmlParser):\n        pass",
  "wiggle-sort": "class Solution:\n    def wiggleSort(self, nums) -> None:\n        pass",
  "word-abbreviation": "class Solution:\n    def wordsAbbreviation(self, words):\n        pass",
  "word-pattern-ii": "class Solution:\n    def wordPatternMatch(self, pattern, s):\n        pass",
  "word-squares": "class Solution:\n    def wordSquares(self, words):\n        pass",
  "zigzag-iterator": "class ZigzagIterator:\n    def __init__(self, v1, v2):\n        pass",
};
